# Generated by Django 4.1.6 on 2023-02-06 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Credito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(max_length=18, verbose_name='CPF')),
                ('nome', models.CharField(max_length=25, verbose_name='Nome')),
                ('valor_solicitado', models.DecimalField(decimal_places=4, max_digits=9, verbose_name='Valor solicitado')),
                ('meses_parcelamento', models.IntegerField(verbose_name='Meses parcelamento')),
                ('dia_pagamento', models.IntegerField(verbose_name='Dia pagamento')),
                ('valor_parcelas', models.DecimalField(blank=True, decimal_places=4, max_digits=9, null=True, verbose_name='Valor da parcela')),
                ('juros', models.DecimalField(blank=True, decimal_places=4, max_digits=9, null=True, verbose_name='Juros')),
                ('renda_necessaria', models.DecimalField(blank=True, decimal_places=4, max_digits=9, null=True, verbose_name='Renda necessária')),
            ],
        ),
    ]
