# Generated by Django 4.1.6 on 2023-02-06 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credito', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credito',
            name='juros',
            field=models.FloatField(blank=True, null=True, verbose_name='Juros'),
        ),
        migrations.AlterField(
            model_name='credito',
            name='renda_necessaria',
            field=models.FloatField(blank=True, null=True, verbose_name='Renda necessária'),
        ),
        migrations.AlterField(
            model_name='credito',
            name='valor_parcelas',
            field=models.FloatField(blank=True, null=True, verbose_name='Valor da parcela'),
        ),
        migrations.AlterField(
            model_name='credito',
            name='valor_solicitado',
            field=models.FloatField(verbose_name='Valor solicitado'),
        ),
    ]
