# Generated by Django 4.1.6 on 2023-02-06 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credito', '0002_alter_credito_juros_alter_credito_renda_necessaria_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='credito',
            name='valor_total',
            field=models.FloatField(blank=True, null=True, verbose_name='Valor total'),
        ),
    ]
